const AuthTypes = {
	SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
	SET_CURRENT_ROLE: 'SET_CURRENT_ROLE',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
	SET_REFRESH_TOKEN: 'SET_REFRESH_TOKEN',
	SET_REMEMBER_ME_STATUS: 'SET_REMEMBER_ME_STATUS',
	SET_SIDER_VISIBILITY: 'SET_SIDER_VISIBILITY',
};

export default AuthTypes;
